# Generated by Django 5.1.6 on 2025-02-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='contact_attachments/%Y/%m/%d/', verbose_name='Прикрепленное изображение'),
        ),
    ]
